name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore Yarn Cache
        uses: actions/cache@v3.0.4
        with:
          path: .yarn/cache
          key: yarn.lock
      - name: Install node modules
        run: yarn install
      - name: Test
        run: yarn test
